export default {
  // home: "line-md:home-md-twotone",
  // layers: "solar:layers-minimalistic-line-duotone",
  // level: "solar:server-minimalistic-bold-duotone",
  // merge: "game-icons:join",
  // noChart: "tabler:chart-bar-off",
  // pdf: "tabler:file-type-pdf",
  // supervisor: "solar:clipboard-bold-duotone",
  // tennis: "game-icons:tennis-racket",
  // toc: "line-md:list-indented",
  // venue: "tabler:building-stadium",
  areaChart: "icon-park-twotone:area-map",
  awards: "game-icons:money-stack",
  awardsOff: "tabler:cash-banknote-off",
  barChart: "solar:chart-2-bold-duotone",
  calendar: "stash:calendar-star-duotone",
  calendarOff: "tabler:calendar-x",
  cards: "icon-park-twotone:view-grid-card",
  category: "icon-park-twotone:category-management",
  coach: "icon-park-twotone:brain",
  colour: "solar:palette-round-bold-duotone",
  columnOff: "tabler:table-minus",
  court: "game-icons:tennis-court",
  download: "line-md:downloading",
  downloading: "line-md:downloading-loop",
  draw: "game-icons:family-tree",
  edit: "line-md:edit-full-twotone",
  filter: "line-md:filter-twotone",
  filterOff: "line-md:filter-off-twotone",
  gauge: "line-md:gauge-twotone-loop",
  globe: "solar:globus-bold-duotone",
  globeOff: "tabler:globe-off",
  group: "solar:link-bold-duotone",
  groupOff: "solar:link-broken-line-duotone",
  h2h: "game-icons:crossed-swords",
  h2hOff: "tabler:sword-off",
  lineChart: "gravity-ui:chart-line",
  one: "solar:cup-first-bold-duotone",
  overview: "icon-park-twotone:view-grid-list",
  people: "icon-park-twotone:peoples-two",
  peopleOff: "solar:user-minus-rounded-line-duotone",
  person: "solar:user-rounded-bold-duotone",
  player: "temaki:tennis",
  polarChart: "solar:round-graph-line-duotone",
  profile: "solar:user-id-bold-duotone",
  scatterChart: "tabler:chart-scatter",
  scores: "icon-park-twotone:scoreboard",
  seeds: "solar:ranking-line-duotone",
  sort: "icon-park-twotone:sort",
  sortAsc: "gravity-ui:bars-ascending-align-left-arrow-down",
  sortDesc: "gravity-ui:bars-descending-align-left-arrow-down",
  stats: "icon-park-twotone:market-analysis",
  table: "icon-park-twotone:table-file",
  tour: "icon-park-twotone:public-toilet",
  trophy: "icon-park-twotone:trophy",
  trophyOff: "tabler:trophy-off",
  umpire: "game-icons:whistle",
  uploading: "line-md:uploading-loop",
  wikipedia: "tabler:brand-wikipedia",
  years: "stash:calendar-duotone"
}
