ALTER TABLE ties
DROP COLUMN country_1_id, DROP COLUMN country_2_id;

ALTER TABLE ties
ADD COLUMN country_1_id TEXT NOT NULL REFERENCES entries (id) ON UPDATE CASCADE ON DELETE CASCADE,
ADD COLUMN country_2_id TEXT NOT NULL REFERENCES entries (id) ON UPDATE CASCADE ON DELETE CASCADE;